version: "3.8"
services:
  kafka:
    image: lensesio/fast-data-dev
    restart: unless-stopped
    environment:
    - ADV_HOST=240.12.0.2
    - RUNNING_SAMPLEDATA=0
    - RUNTESTS=0
    - CONNECT_PORT=0
    networks:
      kafka:
        ipv4_address: 240.12.0.2

  elasticsearch:
    image: elasticsearch:7.7.1
    network_mode: "service:kafka"
    restart: unless-stopped
    environment:
    - discovery.type=single-node

  grafana:
    image: grafana/grafana
    network_mode: "service:kafka"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    network_mode: "service:kafka"
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml 

networks:
  public:
    external: true
  kafka:
    driver: bridge
    ipam:
      config:
      - subnet: 240.12.0.0/24